/// <reference lib="webworker" />

declare const self: ServiceWorkerGlobalScope;

// This will be replaced with the list of files to precache by workbox during build
const wbManifest = self.__WB_MANIFEST;

// Precache all assets generated by the build
workbox.precaching.precacheAndRoute(wbManifest);

// Handle push events
self.addEventListener('push', (event: PushEvent) => {
  if (!event.data) {
    return;
  }

  let data: { title: string; body: string; data?: any };
  try {
    data = event.data.json();
  } catch {
    // Fallback to text if not JSON
    data = {
      title: 'Notification',
      body: event.data.text(),
    };
  }

  const title = data.title || 'Agenda Google';
  const body = data.body || '';
  const icon = '/icons/icon-192.svg';
  const badge = '/icons/icon-72.svg';

  event.waitUntil(
    self.registration.showNotification(title, {
      body,
      icon,
      badge,
      data: data.data,
    })
  );
});

// Handle notification click
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();

  const url = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Check if there's already a window/tab open with the target URL
      for (const client of clientList) {
        if (client.url === url && 'focus' in client) {
          return client.focus();
        }
      }
      // Otherwise open a new window/tab
      if (self.clients.openWindow) {
        return self.clients.openWindow(url);
      }
    })
  );
});